# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json tsconfig.build.json ./
RUN npm install

# Copy source
COPY src ./src
COPY docs ./docs
COPY test-document-storage.js test-document-tools.js test-mcp.js debug.js instructions ./

# Build
RUN npm run build

# Expose stdio by default; entrypoint
CMD ["node", "build/mcp-server.js"]
